### ISSUE TITLE
Publish v1.0.0 Frozen

### ISSUE THREAD

**Issue by suvozy** [RhymeTek/Minima#2]
# Links
- https://github.com/RimeOfficial/jelly-bean
- http://rimeofficial.github.io/jelly-bean/
## Posts
- [x] Tumblr http://rimeofficial.tumblr.com/post/144947670810/jelly-bean-v100-frozen-a-slenderize-two-column
- [x] Twitter https://twitter.com/RimeOfficial/status/735744261308567555
- [x] Instagram https://www.instagram.com/p/BF3a9XYrGit/?taken-by=rimeofficial
- [x] ~~IFTTT - Facebook and Linkedin~~
  - Linkedin
    - https://www.linkedin.com/company/rime-co/comments?topic=6141813899877543936
    - https://www.linkedin.com/company/rime-co/comments?topic=6141814002751234048
    - https://www.linkedin.com/company/rime-co/comments?topic=6141814098486231040
    - https://www.linkedin.com/company/rime-co/comments?topic=6141814246184448000
  - Facebook
    - https://www.facebook.com/RimeOfficial/posts/653883411425649
    - https://www.facebook.com/RimeOfficial/posts/653883764758947
    - https://www.facebook.com/RimeOfficial/posts/653884128092244
    - https://www.facebook.com/RimeOfficial/posts/653884328092224
- [x] Hacker News https://news.ycombinator.com/item?id=11783901
# Inspirations

![jekyll_and_hyde_title](https://cloud.githubusercontent.com/assets/5635088/14707825/586820c8-07e4-11e6-9416-532b0f7bb995.jpg)

[Hyde](http://hyde.getpoole.com/about/)  
In the novel, _The Strange Case of Dr. Jeykll and Mr. Hyde_, Mr. Poole is Dr. Jekyll's virtuous and loyal butler. Similarly, Poole is an upstanding and effective butler that helps you build Jekyll themes. It's made by [@mdo](https://twitter.com/mdo).

---

![51k81zn9y1l](https://cloud.githubusercontent.com/assets/5635088/14700441/3cc3a800-07bd-11e6-9244-4bea3aafba86.jpg)
[Jelly Bean versus Dr. Jekyll & Mr. Hyde](http://www.amazon.com/Jelly-Bean-versus-Jekyll-Hyde/dp/0960129251) June, 1989  
  &mdash; by C. W. Meisterfeld (Author), Darlene Perez (Author), Richard Flinn (Author)

---

![jelly-beans-icicle-mix-2](https://cloud.githubusercontent.com/assets/5635088/14700443/3d250780-07bd-11e6-8120-01b16f262e90.jpg)

---

![932ec52763cca8416443b12c6a8bd392](https://cloud.githubusercontent.com/assets/5635088/14700442/3cfac07e-07bd-11e6-89d6-d92ae362cd73.jpg)
[Frozen](http://frozen.disney.com/) 2013 film

**Comment by suvozit** [comment]
- [ ] Tumblr
- [ ] Twitter
- [ ] Instagram
- [ ] Facebook ??

**Comment by tapojitsaha100** [comment]
- Tumblr http://rimeofficial.tumblr.com/post/144947670810/jelly-bean-v100-frozen-a-slenderize-two-column
- Twitter https://twitter.com/RimeOfficial/status/735744261308567555

**Comment by suvozy** [comment]
# Instagram

Jelly Bean v1.0.0 (Frozen) https://github.com/RimeOfficial/jelly-bean inspiration Disney Frozen 2013 Film #rime #disney #frozen #jellybean #jellybelly #release #github #jekyll #hyde
